name: Weather API

on:
  workflow_dispatch:  # allows manual trigger
  schedule:
    - cron: '0 9 * * *'  # optional: runs every day at 09:00 UTC

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    env:
      CITY_NAME: Mashhad
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run weather script
        run: python weather_API/weather.py
